#!/usr/bin/env python3

import argparse
import os
import sys
import tempfile
import yaml
import shlex
import shutil
import fcntl
import random
import subprocess
from functools import reduce
from collections import defaultdict


XDG_CONFIG_HOME = os.environ.get('XDG_CONFIG_HOME', '$HOME/.config')
XDG_DATA_HOME   = os.environ.get('XDG_DATA_HOME', '$HOME/.local/share')

SANDBOX_ROOT      = f'{XDG_CONFIG_HOME}/sbx'
SANDBOX_HOME      = f'{XDG_DATA_HOME}/sbx/$SANDBOX'
SANDBOX_CONFIG    = f'{SANDBOX_ROOT}/$SANDBOX/config.yml'
SANDBOX_TEMPLATES = f'{XDG_DATA_HOME}/sbx-templates'
DEFAULT_CONFIG    = f'{SANDBOX_ROOT}/global.yml'
APP_BASE       = 'org.sbx'

FLATPAK_INFO   = '''\
[Application]
name=%(app_name)s

[Instance]
instance-id=%(instance_id)s
'''


class SBError(Exception): pass


class Dumper(yaml.Dumper):
  def increase_indent(self, flow = False, indentless = False):
    return super().increase_indent(flow, False)


def fork_and_write(data):
  pr, pw = os.pipe2(0)

  if os.fork() == 0:
    os.close(pr)
    os.write(pw, data.encode())
    sys.exit(0)

  os.close(pw)

  return pr


def copytree(src, dst):
  src = os.path.realpath(src)

  for root, dirs, files in os.walk(src):
    target = os.path.join(dst, root[len(src):])

    for dir in dirs:
      tgtPath = os.path.join(target, dir)
      if not os.path.exists(tgtPath):
        os.makedirs(tgtPath)
        shutil.copystat(os.path.join(root, dir), tgtPath)

    for file in files:
      tgtPath = os.path.join(target, file)
      if not os.path.exists(tgtPath):
        #print('{} -> {}'.format(os.path.join(root, file), tgtPath))
        shutil.copy2(os.path.join(root, file), tgtPath)


def get_pid_ns(pid = os.getpid()):
  link = os.readlink(f'/proc/{pid}/ns/pid')
  return link.split('[')[-1].rstrip(']')


class SBX:
  def __init__(self, args):
    self.args             = args
    self.cmd_args         = []
    self.system_bus_args  = set()
    self.session_bus_args = set()
    self.loaded           = set()
    self.applied          = []
    self.rules            = {}
    self.id               = f'sbx-{random.randint(int(1e9) + 1, int(1e10))}'
    self.runtime_dir      = os.environ['XDG_RUNTIME_DIR']
    self.tempdirs         = set()
    self.die_with_parent  = False


  def log(self, s):
    if self.args.verbose: print(s)


  def expand_path(self, path): return os.path.expanduser(self.expand(path))
  def expand(self, s): return os.path.expandvars(str(s))


  def require_config(self):
    config = self.expand_path(SANDBOX_CONFIG)

    if not os.path.exists(config):
      raise SBError(f'Sandbox "{self.args.name}" does not exists')

    return config


  def load_config(self, path):
    path = self.expand_path(path)

    # Only load config once
    npath = os.path.normpath(path)
    if npath in self.loaded: return
    self.loaded.add(npath)

    if not os.path.exists(path):
      raise SBError(f'Config "{path}" not found')

    self.log(f'Loading config "{path}"')

    with open(path) as f: config = yaml.full_load(f)
    rules = config.get('rules', {})

    if not isinstance(rules, dict):
      raise SBError('"rules" is not a dictionary')

    # Imports
    imports = config.get('imports', [])
    if not isinstance(imports, list):
      raise SBError('"imports" is not a list')

    for imp in imports:
      imp = self.expand_path(imp)
      if not os.path.isabs(imp):
        imp = os.path.relpath(imp, os.path.dirname(path))
      self.load_config(imp)

    # Load rules (overwriting previous)
    for name, rule in rules.items():
      self.rules[name] = rule

    # Save config (overwriting previous)
    self.config = config


  def run_hook(self, name, extra_env = None):
    hook = self.config.get(name)
    if not hook: return 0

    config_dir = os.path.dirname(self.expand_path(SANDBOX_CONFIG))
    env = os.environ.copy()
    env['PATH'] = config_dir + ':' + env.get('PATH', '')
    if extra_env: env.update(extra_env)

    self.log(f'Running {name}: {hook}')
    child = os.fork()
    if child == 0:
      os.execvpe('bash', ['bash', '-c', hook], env)
    _, status = os.waitpid(child, 0)
    return os.waitstatus_to_exitcode(status)


  def apply_rule(self, rule):
    if isinstance(rule, list):
      for r in rule: self.apply_rule(r)
      return

    # Rule names can contain variable references
    rules = self.expand(rule)

    # Only apply each rule once
    if rule in self.applied: return
    self.applied.append(rule)

    self.log(f'Applying rule {rule}')
    self.apply_actions(self.rules[rule])


  def apply_actions(self, actions):
    for action in actions:
      if isinstance(action, dict):
        self.apply_action(action)


  def apply_action(self, action):
    for name, params in action.items():
      method = getattr(self, 'action_' + name.replace('-', '_'), None)

      if method is None:
        raise SBError(f'Unknown action "{name}"')
        sys.exit(1)

      method(params)


  def add_perms(self, params):
    if isinstance(params, dict) and 'perms' in params:
      self.cmd_args.extend(('--perms', f'0{int(params['perms'], 0):o}'))


  def action_use(self, params): self.apply_rule(params)


  def action_args(self, params):
    self.cmd_args.extend((self.expand(a) for a in params))


  def action_die_with_parent(self, params):
    if not isinstance(params, bool):
      raise SBError('"die-with-parent" requires bool')

    self.die_with_parent = params


  def action_env(self, params):
    if isinstance(params, str): params = [params]

    if isinstance(params, dict):
      for k, v in params.items():
        self.cmd_args.extend(('--setenv', k, self.expand(v)))

    elif isinstance(params, list):
      for k in params:
        if k in os.environ:
          self.cmd_args.extend(('--setenv', k, os.environ[k]))


  def create_skel(self, path):
    copytree('/etc/skel', path)
    with open(path + '/.bashrc', 'a') as f:
      f.write(f'\nPS1="({self.args.name}) $PS1"\n')


  def action_skel(self, params):
    if isinstance(params, str): params = {'path': params}
    self.create_skel(self.expand(params['path']))


  def action_tmp_overlay(self, params):
    if isinstance(params, str): params = {'path': params}

    path = self.expand(params['path'])

    if params.get('skel', False):
      tempdir = tempfile.mkdtemp()
      self.tempdirs.add(tempdir)
      shutil.copytree('/etc/skel', tempdir, dirs_exist_ok = True)
      self.cmd_args.extend(('--overlay-src', tempdir))

    self.cmd_args.extend((f'--tmp-overlay', path))


  def action_bind(self, params):
    if isinstance(params, str): params = {'path': params}

    src = os.getcwd() if params.get('cwd', False) else params['path']
    dst = params.get('dst', src)
    src = self.expand(src)
    dst = self.expand(dst)

    create = params.get('create', False)
    if create and not os.path.exists(src):
      os.makedirs(src)
      if create == 'skel': self.create_skel(src)

    if params.get('dev', False): type = 'dev-bind'
    else: type = 'bind' if params.get('read-write', False) else 'ro-bind'
    if params.get('try', False): type += '-try'

    self.add_perms(params)
    self.cmd_args.extend((f'--{type}', src, dst))


  def action_hide(self, params):
    if isinstance(params, str): params = [params]

    for path in params:
      expanded = self.expand_path(path)
      if not os.path.exists(expanded):
        self.log(f'hide: skipping missing path "{expanded}"')
        continue

      if os.path.isdir(expanded):
        self.cmd_args.extend(('--tmpfs', expanded))
      else:
        self.cmd_args.extend(('--ro-bind', '/dev/null', expanded))


  def action_dbus(self, params):
    is_system = params.get('system', False)
    bus_args = self.system_bus_args if is_system else self.session_bus_args

    allow = params.get('allow', [])
    if not isinstance(allow, list): allow = [allow]

    for type in allow:
      assert type in ('see', 'talk', 'own', 'call', 'broadcast')
      bus_args.add(f'--{type}={params['path']}')


  def action_file(self, params):
    if isinstance(params, str): params = dict(path = params)

    fd = fork_and_write(params.get('data', ''))
    self.add_perms(params)
    self.cmd_args.extend(('--file', f'{fd}', self.expand(params['path'])))


  def action_dir(self, params):
    if isinstance(params, str): params = {'path': params}

    self.add_perms(params)
    self.cmd_args.extend(('--dir', self.expand_path(params['path'])))


  def action_symlink(self, params):
    if isinstance(params, str): params = [params, params]
    self.add_perms(params)
    self.cmd_args.extend((
      '--symlink', self.expand(params[0]), self.expand(params[1])))


  def action_chdir(self, params):
    if not isinstance(params, str):
      raise SBError('"chdir" requires string parameter')
    self.cmd_args.extend(('--chdir', self.expand(params)))


  def action_restrict_tty(self, params):
    # --new-session breaks interactive sessions, this is an alternative way of
    # fixing CVE-2017-5226

    try:
      import seccomp
    except ImportError:
      import pyseccomp as seccomp
    import termios

    f = seccomp.SyscallFilter(defaction = seccomp.ALLOW)
    f.add_rule(seccomp.KILL_PROCESS, 'ioctl',
               seccomp.Arg(1, seccomp.MASKED_EQ, 0xffffffff, termios.TIOCSTI))
    f.add_rule(seccomp.KILL_PROCESS, 'ioctl',
               seccomp.Arg(1, seccomp.MASKED_EQ, 0xffffffff, termios.TIOCLINUX))
    f.load()


  def action_ifeq(self, params, ifneq = False):
    if not isinstance(params, list) or len(params) < 2:
      raise SBError(
        f'"if{'n' if ifneq else ''}eq" requires a list with at least 2 ' +
        'elements')

    if (self.expand(params[0]) == self.expand(params[1])) != ifneq:
      self.apply_actions(params[2:])


  def action_ifneq(self, params): self.action_ifeq(params, True)


  def action_ifdef(self, params):
    if not isinstance(params, list) or len(params) < 1:
      raise SBError('"ifdef" requires a non-empty list')

    if params[0] in os.environ: self.apply_actions(params[1:])


  def fs_arg(self, params, name):
    if isinstance(params, str): path = params
    elif isinstance(params, dict):
      path = params.get('path')
      self.add_perms(params)
    else: raise SBError(f'"{name}" requires string or dict parameter')

    self.cmd_args.extend((f'--{name}', self.expand_path(path)))


  def action_dev(self,  params):  self.fs_arg(params, 'dev')
  def action_proc(self, params):  self.fs_arg(params, 'proc')


  def action_tmpfs(self, params):
    if isinstance(params, dict) and 'size' in params:
      self.cmd_args.extend(('--size', self.expand(params['size'])))

    self.fs_arg(params, 'tmpfs')


  def setup_dbus_proxy(self):
    if not (self.session_bus_args or self.system_bus_args): return

    args = []
    dir  = f'{self.runtime_dir}/xdg-dbus-proxy'

    os.makedirs(dir, exist_ok = True)

    if self.session_bus_args:
      socket   = tempfile.mktemp(prefix = 'session-', dir = dir)
      bus_addr = os.environ['DBUS_SESSION_BUS_ADDRESS']
      args.extend([bus_addr, socket, '--filter'] + list(self.session_bus_args))
      self.cmd_args.extend((
        '--bind', socket, bus_addr.removeprefix('unix:path='),
        '--setenv', 'DBUS_SESSION_BUS_ADDRESS', bus_addr))

    if self.system_bus_args:
      socket = tempfile.mktemp(prefix = 'system-', dir = dir)
      path   = '/run/dbus/system_bus_socket'
      args.extend([path, socket, '--filter'] + list(self.system_bus_args))
      self.cmd_args.extend(('--bind', path, path))

    if self.args.verbose: args.append('--log')

    # Wrap proxy
    data = {'app_name': os.environ['APP_NAME'], 'instance_id': self.id}
    data = FLATPAK_INFO % data
    fd = fork_and_write(data)
    cmd = ['bwrap', '--new-session', '--symlink', '/usr/lib64', '/lib64',
      '--ro-bind', '/usr/lib', '/usr/lib', '--ro-bind', '/usr/lib64',
      '/usr/lib64', '--ro-bind', '/usr/bin', '/usr/bin', '--clearenv',
      '--bind', self.runtime_dir, self.runtime_dir,
      '--ro-bind-data', f'{fd}', '/.flatpak-info',
      '--die-with-parent', '--']

    # Start dbus proxy
    pr, pw = os.pipe2(0)
    cmd += ['xdg-dbus-proxy', f'--fd={pw}'] + args

    if os.fork() == 0:
      os.close(pr)
      os.execlp(cmd[0], *cmd)

    os.close(pw)
    if os.read(pr, 1) != b'x': # wait for xdg-dbus-proxy to be ready
      raise SBError('Failed to start xdg-dbus-proxy')

    self.cmd_args.extend(('--sync-fd', f'{pr}'))


  def run(self):
    # Load config
    self.require_config()
    self.load_config(SANDBOX_CONFIG)

    # Pre-run hook
    rc = self.run_hook('pre-hook')
    if rc != 0: sys.exit(rc)

    # Command
    if self.args.command: command = [self.args.command]
    else:
      if not 'command' in self.config:
        raise SBError('Sandbox config is missing "command"')
      command = self.config['command']
    command += self.args.args

    exp_command = [self.expand(arg) for arg in command]
    os.environ['SANDBOX_CMD'] = shlex.join(exp_command)
    os.environ['SANDBOX_EXE'] = exp_command[0]

    # Apply rules
    self.apply_rule(self.config.get('use', []))
    self.setup_dbus_proxy()

    # Die with parent
    if self.die_with_parent: self.cmd_args.append('--die-with-parent')

    # Create bwrapinfo.json
    info_path = f'{self.runtime_dir}/.flatpak/{self.id}/bwrapinfo.json'
    os.makedirs(os.path.dirname(info_path), exist_ok = True)
    info_fd = open(info_path, 'w')
    fcntl.fcntl(info_fd, fcntl.F_SETFD, 0)
    self.cmd_args += ['--info-fd', f'{info_fd.fileno()}']

    # Build command (wrap in login shell so ~/.profile is sourced)
    cmd = ['bwrap'] + self.cmd_args + ['bash', '-lc', shlex.join(exp_command)]
    self.log('@' + shlex.join(cmd))

    # Execute
    child = os.fork()
    if child == 0:
      os.environ['SBX_ROOT_PID'] = str(os.getpid())
      os.execvp(cmd[0], cmd)
    _, status = os.waitpid(child, 0)
    exit_code = os.waitstatus_to_exitcode(status)

    # Cleanup temp dirs
    for path in self.tempdirs:
      shutil.rmtree(path)

    # Post-run hook
    rc = self.run_hook('post-hook', {'SANDBOX_EXIT_CODE': str(exit_code)})
    sys.exit(rc if rc != 0 else exit_code)


  def create(self):
    # Check sandbox config
    sandbox_config = self.expand_path(SANDBOX_CONFIG)
    if os.path.exists(sandbox_config):
      raise SBError(f'Sandbox "{self.args.name}" already exists')

    # Template and --config are mutually exclusive
    if self.args.template and self.args.config:
      raise SBError('--template and --config are mutually exclusive')

    # --template forbids --rule and command overrides (copied verbatim)
    if self.args.template and (self.args.rule or self.args.command):
      raise SBError('--template cannot be combined with --rule or command')

    config_dir = os.path.dirname(sandbox_config)
    os.makedirs(config_dir, exist_ok = True)

    if self.args.template:
      template_dir = self.expand_path(
        f'{SANDBOX_TEMPLATES}/{self.args.template}')
      if not os.path.isdir(template_dir):
        raise SBError(f'Template "{self.args.template}" not found')

      template_config = f'{template_dir}/config.yml'
      if not os.path.isfile(template_config):
        raise SBError(f'Template "{self.args.template}" missing config.yml')

      # Copy template contents verbatim (config.yml, hook scripts, etc.)
      # Skip 'home/' which is seeded separately into SANDBOX_HOME.
      for entry in os.listdir(template_dir):
        if entry == 'home': continue
        src = os.path.join(template_dir, entry)
        dst = os.path.join(config_dir, entry)
        if os.path.isdir(src): shutil.copytree(src, dst, symlinks = True)
        else: shutil.copy2(src, dst)

      # Seed home from template
      template_home = f'{template_dir}/home'
      if os.path.isdir(template_home):
        sandbox_home = self.expand_path(SANDBOX_HOME)
        if os.path.exists(sandbox_home):
          raise SBError(
            f'Sandbox home "{sandbox_home}" already exists; refusing to ' +
            'seed from template')
        shutil.copytree(template_home, sandbox_home, symlinks = True)

      # Load the newly-installed config so hooks can fire
      self.load_config(SANDBOX_CONFIG)

    else:
      # --config or default: synthesize config_data, inline or import rules
      config = self.args.config if self.args.config else DEFAULT_CONFIG
      self.load_config(config)

      command = self.args.command or self.config.get('command', ['bash'])
      rules   = self.args.rule    or self.config.get('use', [])
      config_data = dict(use = rules, command = command)

      if self.args.config: config_data['rules']   = self.rules
      else:                config_data['imports'] = [config]

      with open(sandbox_config, 'w') as f:
        yaml.dump(
          config_data, f, Dumper = Dumper, width = 80, sort_keys = False,
          default_flow_style = False)

    rc = self.run_hook('create-hook')
    if rc != 0: sys.exit(rc)


  def list(self):
    root = self.expand_path(SANDBOX_ROOT)
    names = []

    for name in os.listdir(root):
      path = f'{root}/{name}'
      if os.path.isdir(path) and os.path.exists(f'{path}/config.yml'):
        names.append(name)

    for name in sorted(names): print(name)


  def list_rules(self):
    # Load default config
    config = self.args.config if self.args.config else DEFAULT_CONFIG
    self.load_config(config)

    width = reduce(lambda x, name: max(len(name), x), self.rules, 0)

    for rule in sorted(self.rules):
      help = ''

      first = self.rules[rule][:1]
      if len(first) and isinstance(first[0], str): help = first[0]

      use = []
      for action in self.rules[rule]:
        if isinstance(action, dict):
          for name, params in action.items():
            if name == 'use':
              if isinstance(params, str): use.append(params)
              else: use += params

      if len(use):
        if help: help = help + ' '
        help += f'(Uses: {' '.join(use)})'

      if help: print(f'{rule:<{width}} - {help}')
      else: print(rule)


  def ps(self):
    # Dictionary to group processes by their PID namespace inode
    ns_groups = defaultdict(list)
    our_ns_inode = get_pid_ns()

    # Iterate through all entries in /proc
    for pid_dir in os.listdir('/proc'):
      if not pid_dir.isdigit(): continue

      pid = int(pid_dir)
      path = f'/proc/{pid}'

      try:
        # Check if the process name is 'bwrap'
        with open(f'{path}/comm', 'r', errors='ignore') as f:
          if f.read().strip() != 'bwrap': continue

        # Filter by the environment variable SBX_ROOT_PID
        name  = None
        valid = False
        with open(f'{path}/environ', 'r', errors = 'ignore') as f:
          env = f.read().split('\0')
          for var in env:
            if   var.startswith('SANDBOX='):      name  = var[8:]
            elif var.startswith('SBX_ROOT_PID='): valid = True

        if valid is None: continue

        # Get the PID namespace identifier
        ns_inode = get_pid_ns(pid)
        if ns_inode == our_ns_inode: continue

        # Get the process start time to determine age
        with open(f'{path}/stat', 'r', errors='ignore') as f:
          stat_fields = f.read().split()
          # Use field 21 (0-indexed) which corresponds to the 22nd field
          start_time = int(stat_fields[21])

        # Group the verified process
        ns_groups[ns_inode].append((pid, start_time, name))

      except (FileNotFoundError, ProcessLookupError, PermissionError,
              IndexError, ValueError): continue

    # Extract the oldest PID from each shared PID namespace group
    entries = []
    for ns_inode, procs in ns_groups.items():
      procs.sort(key = lambda x: x[1])
      entries.append((procs[0][2], procs[0][0]))

    width = max((len(str(p)) for _, p in entries), default = 4)
    print(f'{"PID":<{width}} SANDBOX')
    for name, pid in sorted(entries):
      print(f'{pid:<{width}} {name}')


  def delete(self):
    config = self.require_config()
    self.load_config(SANDBOX_CONFIG)

    # Delete hook (fires before any rmtree)
    rc = self.run_hook('delete-hook')
    if rc != 0: sys.exit(rc)

    paths = [os.path.dirname(config)]
    home = self.expand_path(SANDBOX_HOME)
    if os.path.isdir(home): paths.append(home)

    for path in paths: self.log(f'Preparing to delete "{path}"')

    if not self.args.force:
      response = input(f'Delete sandbox "{self.args.name}"? [Yes/No] ')
      if not response.lower() in ('yes', 'y'): return

    for path in paths: shutil.rmtree(path)


  def show(self):
    with open(self.require_config(), 'r') as f:
      sys.stdout.write(f.read())


  def template(self):
    config = self.require_config()
    target = self.expand_path(
      f'{SANDBOX_TEMPLATES}/{self.args.template_name}')

    if os.path.exists(target):
      if not self.args.force:
        raise SBError(
          f'Template "{self.args.template_name}" already exists; use ' +
          '--force to overwrite')
      shutil.rmtree(target)

    os.makedirs(target)

    # Copy entire sandbox config dir (config.yml + any hook scripts)
    config_dir = os.path.dirname(config)
    for entry in os.listdir(config_dir):
      src = os.path.join(config_dir, entry)
      dst = os.path.join(target, entry)
      if os.path.isdir(src): shutil.copytree(src, dst, symlinks = True)
      else: shutil.copy2(src, dst)

    home = self.expand_path(SANDBOX_HOME)
    if os.path.isdir(home):
      shutil.copytree(home, f'{target}/home', symlinks = True)


  def edit(self):
    if not 'EDITOR' in os.environ: editor = 'vi'
    else: editor = os.environ['EDITOR']

    if not shutil.which(editor):
      raise SBError('"EDITOR" environment variable set to invalid command')

    cmd = [editor, self.require_config()]
    os.execvp(cmd[0], cmd)


  def enter(self):
    tpid = str(self.args.pid)
    stat = os.stat(f'/proc/{tpid}')
    tuid = str(stat.st_uid)
    tgid = str(stat.st_gid)
    tcwd = os.readlink(f'/proc/{tpid}/cwd')
    cmd  = []

    if os.getuid():
      if not shutil.which('sudo'):
        raise SBError('"sudo" not found on PATH')

      cmd += ['sudo']

    if not shutil.which('nsenter'):
      raise SBError('"nsenter" not found on PATH')

    cmd += ['nsenter', '-t', tpid, '-e']

    if self.args.root:
      cmd += ['--mount', '--uts', '--ipc', '--net', '--pid']
    else: cmd += ['-a', '-S', tuid, '-G', tgid]

    cmd += ['/bin/bash', '-c', f'cd "{tcwd}" && exec /bin/bash -l']

    os.execvp(cmd[0], cmd)


  def exec(self):
    if hasattr(self.args, 'name'):
      os.environ['SANDBOX']        = self.args.name
      os.environ['SANDBOX_HOME']   = self.expand(SANDBOX_HOME)
      os.environ['SANDBOX_CONFIG'] = self.expand(SANDBOX_CONFIG)
      os.environ['APP_NAME']       = f'{APP_BASE}.{self.args.name}'

    os.environ['SANDBOX_ROOT'] = self.expand(SANDBOX_ROOT)

    getattr(self, self.args.cmd.replace('-', '_'))()


# Arguments
desc = '''\
sbx is a tool for creating sandboxes in user space.\
'''

parser = argparse.ArgumentParser(description = desc)
parser.add_argument(
  '--verbose', '-v', action = 'store_true', help = 'enable verbose logging')
subs = parser.add_subparsers(dest = 'cmd', metavar = '<subcommand>')

create_parser = subs.add_parser('create', help = 'create a new sandbox')
create_parser.add_argument(
  '--config', '-c', help = 'override the default config file and copy the ' +
  'rules to the new sandbox rather than import them')
create_parser.add_argument(
  '--template', '-t', help = 'create the sandbox from a template in ' +
  f'{SANDBOX_TEMPLATES}; mutually exclusive with --config')
create_parser.add_argument(
  '--rule', '-r', action = 'append', help = 'rule or rules to apply ' +
  'instead of the default rules')
create_parser.add_argument('name', help = 'name of the sandbox')
create_parser.add_argument(
  'command', nargs = '*', help = 'the command to run and optional arguments, ' +
  'defaults are used if not specified')

run_parser = subs.add_parser('run', help = 'run an existing sandbox')
run_parser.add_argument('name', help = 'name of the sandbox')
run_parser.add_argument(
  '--command', '-C', help = 'override the sandbox command')
run_parser.add_argument('args', nargs = '*',
  help = 'optional additional arguments to pass to the sandbox command')

subs.add_parser('list', help = 'list existing sandboxes')
subs.add_parser('ps',   help = 'list running sandboxes')

lr_parser = subs.add_parser('list-rules', help = 'list available rules')
lr_parser.add_argument('--config', '-c', help = 'override the default config')

del_parser = subs.add_parser('delete', help = 'delete an existing sandbox')
del_parser.add_argument('name', help = 'name of the sandbox')
del_parser.add_argument(
  '--force', '-f', action = 'store_true', help = 'delete without asking')

show_parser = subs.add_parser('show', help = 'print sandbox config and exit')
show_parser.add_argument('name', help = 'name of the sandbox')

edit_parser = subs.add_parser('edit', help = 'edit sandbox config')
edit_parser.add_argument('name', help = 'name of the sandbox')

tpl_parser = subs.add_parser(
  'template', help = 'create a template from an existing sandbox')
tpl_parser.add_argument('name', help = 'name of the source sandbox')
tpl_parser.add_argument('template_name', help = 'name of the new template')
tpl_parser.add_argument(
  '--force', '-f', action = 'store_true',
  help = 'overwrite the template if it already exists')

ent_parser = subs.add_parser('enter', help = 'enter a running container')
ent_parser.add_argument('pid', type = int, help = 'Process ID')
ent_parser.add_argument(
  '--root', '-r', action = 'store_true', help = 'enter as root user')

subs.add_parser('help', help = 'show this help message and exit')

args = parser.parse_args()

if args.cmd is None or args.cmd == 'help':
  parser.print_help()
  sys.exit(1)

try:
  SBX(args).exec()

except SBError as e:
  print(f'ERROR: {str(e)}.', file = sys.stderr)
  sys.exit(1)
